version: '3.8'
services:
  django-api:
    build: ./backend/django-api
    volumes:
      - ./backend/django-api:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/django

  nodejs-api:
    build: ./backend/nodejs-api
    volumes:
      - ./backend/nodejs-api:/src
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django

  mongodb:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  postgres_data:
  mongo_data:
